// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterDomain(Registration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegate(Delegation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireDomain(Retirement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetPolicy(Policy);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SetProjection(ProjectionDeclaration);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainRegistered(Domain);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationSet {
    pub delegation_name: DelegationName,
    pub domain: Domain,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainRetired(Domain);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicySet(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionSet {
    pub domain: Domain,
    pub record_count: Integer,
    pub redirect_count: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected {
    pub operation: OperationKind,
    pub reason: RejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration(Domain);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegation {
    pub delegation_name: DelegationName,
    pub domain: Domain,
    pub delegation_target: DelegationTarget,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retirement(Domain);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProjectionDirective {
    Enable,
    Disable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionPolicy {
    pub domain: Domain,
    pub projection_scope: ProjectionScope,
    pub projection_directive: ProjectionDirective,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Policy(Vec<ProjectionPolicy>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionDeclaration {
    pub domain: Domain,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    DomainAlreadyRegistered,
    DomainUnknown,
    DelegationAlreadyExists,
    DelegationUnknown,
    ProjectionUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Domain(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationTarget(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordValue(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UniformResourceLocator(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProjectionScope {
    PublicRecords,
    RedirectRules,
    Everything,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RecordKind {
    AddressV4,
    AddressV6,
    CanonicalName,
    Text,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PathTreatment {
    Preserve,
    Replace,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub name: DomainName,
    pub record_kind: RecordKind,
    pub value: RecordValue,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub source: DomainName,
    pub target: UniformResourceLocator,
    pub redirect_status: RedirectStatus,
    pub path_treatment: PathTreatment,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    RegisterDomain(RegisterDomain),
    Delegate(Delegate),
    RetireDomain(RetireDomain),
    SetPolicy(SetPolicy),
    SetProjection(SetProjection),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    DomainRegistered(DomainRegistered),
    DelegationSet(DelegationSet),
    DomainRetired(DomainRetired),
    PolicySet(PolicySet),
    ProjectionSet(ProjectionSet),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
impl RegisterDomain {
    pub fn new(payload: Registration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Registration {
        &self.0
    }
    pub fn into_payload(self) -> Registration {
        self.0
    }
}
#[rustfmt::skip]
impl From<Registration> for RegisterDomain {
    fn from(payload: Registration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Delegate {
    pub fn new(payload: Delegation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Delegation {
        &self.0
    }
    pub fn into_payload(self) -> Delegation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Delegation> for Delegate {
    fn from(payload: Delegation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireDomain {
    pub fn new(payload: Retirement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Retirement {
        &self.0
    }
    pub fn into_payload(self) -> Retirement {
        self.0
    }
}
#[rustfmt::skip]
impl From<Retirement> for RetireDomain {
    fn from(payload: Retirement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetPolicy {
    pub fn new(payload: Policy) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Policy {
        &self.0
    }
    pub fn into_payload(self) -> Policy {
        self.0
    }
}
#[rustfmt::skip]
impl From<Policy> for SetPolicy {
    fn from(payload: Policy) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SetProjection {
    pub fn new(payload: ProjectionDeclaration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProjectionDeclaration {
        &self.0
    }
    pub fn into_payload(self) -> ProjectionDeclaration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProjectionDeclaration> for SetProjection {
    fn from(payload: ProjectionDeclaration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainRegistered {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
#[rustfmt::skip]
impl From<Domain> for DomainRegistered {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainRetired {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
#[rustfmt::skip]
impl From<Domain> for DomainRetired {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PolicySet {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for PolicySet {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Registration {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
#[rustfmt::skip]
impl From<Domain> for Registration {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retirement {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
#[rustfmt::skip]
impl From<Domain> for Retirement {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Policy {
    pub fn new(payload: Vec<ProjectionPolicy>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ProjectionPolicy> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ProjectionPolicy> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ProjectionPolicy>> for Policy {
    fn from(payload: Vec<ProjectionPolicy>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Domain {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Domain {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DomainName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DelegationName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationTarget {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DelegationTarget {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RecordValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UniformResourceLocator {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UniformResourceLocator {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn register_domain(payload: Registration) -> Self {
        Self::RegisterDomain(RegisterDomain::new(payload))
    }
    pub fn delegate(payload: Delegation) -> Self {
        Self::Delegate(Delegate::new(payload))
    }
    pub fn retire_domain(payload: Retirement) -> Self {
        Self::RetireDomain(RetireDomain::new(payload))
    }
    pub fn set_policy(payload: Policy) -> Self {
        Self::SetPolicy(SetPolicy::new(payload))
    }
    pub fn set_projection(payload: ProjectionDeclaration) -> Self {
        Self::SetProjection(SetProjection::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn domain_registered(payload: Domain) -> Self {
        Self::DomainRegistered(DomainRegistered::new(payload))
    }
    pub fn delegation_set(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
    pub fn domain_retired(payload: Domain) -> Self {
        Self::DomainRetired(DomainRetired::new(payload))
    }
    pub fn policy_set(payload: Integer) -> Self {
        Self::PolicySet(PolicySet::new(payload))
    }
    pub fn projection_set(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterDomain> for Input {
    fn from(payload: RegisterDomain) -> Self {
        Self::RegisterDomain(payload)
    }
}

#[rustfmt::skip]
impl From<Delegate> for Input {
    fn from(payload: Delegate) -> Self {
        Self::Delegate(payload)
    }
}

#[rustfmt::skip]
impl From<RetireDomain> for Input {
    fn from(payload: RetireDomain) -> Self {
        Self::RetireDomain(payload)
    }
}

#[rustfmt::skip]
impl From<SetPolicy> for Input {
    fn from(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }
}

#[rustfmt::skip]
impl From<SetProjection> for Input {
    fn from(payload: SetProjection) -> Self {
        Self::SetProjection(payload)
    }
}

#[rustfmt::skip]
impl From<DomainRegistered> for Output {
    fn from(payload: DomainRegistered) -> Self {
        Self::DomainRegistered(payload)
    }
}

#[rustfmt::skip]
impl From<DelegationSet> for Output {
    fn from(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
}

#[rustfmt::skip]
impl From<DomainRetired> for Output {
    fn from(payload: DomainRetired) -> Self {
        Self::DomainRetired(payload)
    }
}

#[rustfmt::skip]
impl From<PolicySet> for Output {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

#[rustfmt::skip]
impl From<ProjectionSet> for Output {
    fn from(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
}

#[rustfmt::skip]
impl From<RequestRejected> for Output {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_REGISTER_DOMAIN: u64 = 0x0000000000000000;
    pub const INPUT_DELEGATE: u64 = 0x0001000000000000;
    pub const INPUT_RETIRE_DOMAIN: u64 = 0x0002000000000000;
    pub const INPUT_SET_POLICY: u64 = 0x0003000000000000;
    pub const INPUT_SET_PROJECTION: u64 = 0x0004000000000000;
    pub const OUTPUT_DOMAIN_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_DELEGATION_SET: u64 = 0x0101000000000000;
    pub const OUTPUT_DOMAIN_RETIRED: u64 = 0x0102000000000000;
    pub const OUTPUT_POLICY_SET: u64 = 0x0103000000000000;
    pub const OUTPUT_PROJECTION_SET: u64 = 0x0104000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0105000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    DomainRegistered,
    DelegationSet,
    DomainRetired,
    PolicySet,
    ProjectionSet,
    RequestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::RegisterDomain(_) => InputRoute::RegisterDomain,
            Self::Delegate(_) => InputRoute::Delegate,
            Self::RetireDomain(_) => InputRoute::RetireDomain,
            Self::SetPolicy(_) => InputRoute::SetPolicy,
            Self::SetProjection(_) => InputRoute::SetProjection,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RegisterDomain(_) => short_header::INPUT_REGISTER_DOMAIN,
            Self::Delegate(_) => short_header::INPUT_DELEGATE,
            Self::RetireDomain(_) => short_header::INPUT_RETIRE_DOMAIN,
            Self::SetPolicy(_) => short_header::INPUT_SET_POLICY,
            Self::SetProjection(_) => short_header::INPUT_SET_PROJECTION,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER_DOMAIN => Ok(InputRoute::RegisterDomain),
            short_header::INPUT_DELEGATE => Ok(InputRoute::Delegate),
            short_header::INPUT_RETIRE_DOMAIN => Ok(InputRoute::RetireDomain),
            short_header::INPUT_SET_POLICY => Ok(InputRoute::SetPolicy),
            short_header::INPUT_SET_PROJECTION => Ok(InputRoute::SetProjection),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::DomainRegistered(_) => OutputRoute::DomainRegistered,
            Self::DelegationSet(_) => OutputRoute::DelegationSet,
            Self::DomainRetired(_) => OutputRoute::DomainRetired,
            Self::PolicySet(_) => OutputRoute::PolicySet,
            Self::ProjectionSet(_) => OutputRoute::ProjectionSet,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::DomainRegistered(_) => short_header::OUTPUT_DOMAIN_REGISTERED,
            Self::DelegationSet(_) => short_header::OUTPUT_DELEGATION_SET,
            Self::DomainRetired(_) => short_header::OUTPUT_DOMAIN_RETIRED,
            Self::PolicySet(_) => short_header::OUTPUT_POLICY_SET,
            Self::ProjectionSet(_) => short_header::OUTPUT_PROJECTION_SET,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_DOMAIN_REGISTERED => Ok(OutputRoute::DomainRegistered),
            short_header::OUTPUT_DELEGATION_SET => Ok(OutputRoute::DelegationSet),
            short_header::OUTPUT_DOMAIN_RETIRED => Ok(OutputRoute::DomainRetired),
            short_header::OUTPUT_POLICY_SET => Ok(OutputRoute::PolicySet),
            short_header::OUTPUT_PROJECTION_SET => Ok(OutputRoute::ProjectionSet),
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "RegisterDomain",
        "Delegate",
        "RetireDomain",
        "SetPolicy",
        "SetProjection",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
