// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

pub type RegisterDomain = Registration;

pub type Delegate = Delegation;

pub type RetireDomain = Retirement;

pub type SetPolicy = Policy;

pub type SetProjection = ProjectionDeclaration;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainRegistered(pub Domain);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationSet {
    pub delegation_name: DelegationName,
    pub domain: Domain,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainRetired(pub Domain);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PolicySet(pub Integer);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionSet {
    pub domain: Domain,
    pub record_count: Integer,
    pub redirect_count: Integer,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected {
    pub operation: OperationKind,
    pub reason: RejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Registration(pub Domain);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegation {
    pub delegation_name: DelegationName,
    pub domain: Domain,
    pub delegation_target: DelegationTarget,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retirement(pub Domain);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProjectionDirective {
    Enable,
    Disable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionPolicy {
    pub domain: Domain,
    pub projection_scope: ProjectionScope,
    pub projection_directive: ProjectionDirective,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Policy(pub Vec<ProjectionPolicy>);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionDeclaration {
    pub domain: Domain,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    DomainAlreadyRegistered,
    DomainUnknown,
    DelegationAlreadyExists,
    DelegationUnknown,
    ProjectionUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OperationKind {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

pub type Domain = String;

pub type DomainName = String;

pub type DelegationName = String;

pub type DelegationTarget = String;

pub type RecordValue = String;

pub type UniformResourceLocator = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProjectionScope {
    PublicRecords,
    RedirectRules,
    Everything,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RecordKind {
    AddressV4,
    AddressV6,
    CanonicalName,
    Text,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PathTreatment {
    Preserve,
    Replace,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub name: DomainName,
    pub record_kind: RecordKind,
    pub value: RecordValue,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub source: DomainName,
    pub target: UniformResourceLocator,
    pub redirect_status: RedirectStatus,
    pub path_treatment: PathTreatment,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    RegisterDomain(RegisterDomain),
    Delegate(Delegate),
    RetireDomain(RetireDomain),
    SetPolicy(SetPolicy),
    SetProjection(SetProjection),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    DomainRegistered(DomainRegistered),
    DelegationSet(DelegationSet),
    DomainRetired(DomainRetired),
    PolicySet(PolicySet),
    ProjectionSet(ProjectionSet),
    RequestRejected(RequestRejected),
}

impl DomainRegistered {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
impl From<Domain> for DomainRegistered {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

impl DomainRetired {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
impl From<Domain> for DomainRetired {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

impl PolicySet {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
impl From<Integer> for PolicySet {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

impl Registration {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
impl From<Domain> for Registration {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

impl Retirement {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
impl From<Domain> for Retirement {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

impl Policy {
    pub fn new(payload: Vec<ProjectionPolicy>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ProjectionPolicy> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ProjectionPolicy> {
        self.0
    }
}
impl From<Vec<ProjectionPolicy>> for Policy {
    fn from(payload: Vec<ProjectionPolicy>) -> Self {
        Self::new(payload)
    }
}

impl Input {
    pub fn register_domain(payload: RegisterDomain) -> Self {
        Self::RegisterDomain(payload)
    }
    pub fn delegate(payload: Delegate) -> Self {
        Self::Delegate(payload)
    }
    pub fn retire_domain(payload: RetireDomain) -> Self {
        Self::RetireDomain(payload)
    }
    pub fn set_policy(payload: SetPolicy) -> Self {
        Self::SetPolicy(payload)
    }
    pub fn set_projection(payload: SetProjection) -> Self {
        Self::SetProjection(payload)
    }
}

impl Output {
    pub fn domain_registered(payload: Domain) -> Self {
        Self::DomainRegistered(DomainRegistered::new(payload))
    }
    pub fn delegation_set(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
    pub fn domain_retired(payload: Domain) -> Self {
        Self::DomainRetired(DomainRetired::new(payload))
    }
    pub fn policy_set(payload: Integer) -> Self {
        Self::PolicySet(PolicySet::new(payload))
    }
    pub fn projection_set(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

impl From<DomainRegistered> for Output {
    fn from(payload: DomainRegistered) -> Self {
        Self::DomainRegistered(payload)
    }
}

impl From<DelegationSet> for Output {
    fn from(payload: DelegationSet) -> Self {
        Self::DelegationSet(payload)
    }
}

impl From<DomainRetired> for Output {
    fn from(payload: DomainRetired) -> Self {
        Self::DomainRetired(payload)
    }
}

impl From<PolicySet> for Output {
    fn from(payload: PolicySet) -> Self {
        Self::PolicySet(payload)
    }
}

impl From<ProjectionSet> for Output {
    fn from(payload: ProjectionSet) -> Self {
        Self::ProjectionSet(payload)
    }
}

impl From<RequestRejected> for Output {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[cfg(feature = "nota-text")]
impl DomainRegistered {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DelegationSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DomainRetired {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PolicySet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionSet {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RequestRejected {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Registration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Delegation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Retirement {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionDirective {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionPolicy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Policy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionDeclaration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ProjectionScope {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RecordKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RedirectStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PathTreatment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DomainNameSystemRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RedirectRule {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_REGISTER_DOMAIN: u64 = 0x0000000000000000;
    pub const INPUT_DELEGATE: u64 = 0x0001000000000000;
    pub const INPUT_RETIRE_DOMAIN: u64 = 0x0002000000000000;
    pub const INPUT_SET_POLICY: u64 = 0x0003000000000000;
    pub const INPUT_SET_PROJECTION: u64 = 0x0004000000000000;
    pub const OUTPUT_DOMAIN_REGISTERED: u64 = 0x0100000000000000;
    pub const OUTPUT_DELEGATION_SET: u64 = 0x0101000000000000;
    pub const OUTPUT_DOMAIN_RETIRED: u64 = 0x0102000000000000;
    pub const OUTPUT_POLICY_SET: u64 = 0x0103000000000000;
    pub const OUTPUT_PROJECTION_SET: u64 = 0x0104000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0105000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    RegisterDomain,
    Delegate,
    RetireDomain,
    SetPolicy,
    SetProjection,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    DomainRegistered,
    DelegationSet,
    DomainRetired,
    PolicySet,
    ProjectionSet,
    RequestRejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::RegisterDomain(_) => InputRoute::RegisterDomain,
            Self::Delegate(_) => InputRoute::Delegate,
            Self::RetireDomain(_) => InputRoute::RetireDomain,
            Self::SetPolicy(_) => InputRoute::SetPolicy,
            Self::SetProjection(_) => InputRoute::SetProjection,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::RegisterDomain(_) => short_header::INPUT_REGISTER_DOMAIN,
            Self::Delegate(_) => short_header::INPUT_DELEGATE,
            Self::RetireDomain(_) => short_header::INPUT_RETIRE_DOMAIN,
            Self::SetPolicy(_) => short_header::INPUT_SET_POLICY,
            Self::SetProjection(_) => short_header::INPUT_SET_PROJECTION,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_REGISTER_DOMAIN => Ok(InputRoute::RegisterDomain),
            short_header::INPUT_DELEGATE => Ok(InputRoute::Delegate),
            short_header::INPUT_RETIRE_DOMAIN => Ok(InputRoute::RetireDomain),
            short_header::INPUT_SET_POLICY => Ok(InputRoute::SetPolicy),
            short_header::INPUT_SET_PROJECTION => Ok(InputRoute::SetProjection),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::DomainRegistered(_) => OutputRoute::DomainRegistered,
            Self::DelegationSet(_) => OutputRoute::DelegationSet,
            Self::DomainRetired(_) => OutputRoute::DomainRetired,
            Self::PolicySet(_) => OutputRoute::PolicySet,
            Self::ProjectionSet(_) => OutputRoute::ProjectionSet,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::DomainRegistered(_) => short_header::OUTPUT_DOMAIN_REGISTERED,
            Self::DelegationSet(_) => short_header::OUTPUT_DELEGATION_SET,
            Self::DomainRetired(_) => short_header::OUTPUT_DOMAIN_RETIRED,
            Self::PolicySet(_) => short_header::OUTPUT_POLICY_SET,
            Self::ProjectionSet(_) => short_header::OUTPUT_PROJECTION_SET,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_DOMAIN_REGISTERED => Ok(OutputRoute::DomainRegistered),
            short_header::OUTPUT_DELEGATION_SET => Ok(OutputRoute::DelegationSet),
            short_header::OUTPUT_DOMAIN_RETIRED => Ok(OutputRoute::DomainRetired),
            short_header::OUTPUT_POLICY_SET => Ok(OutputRoute::PolicySet),
            short_header::OUTPUT_PROJECTION_SET => Ok(OutputRoute::ProjectionSet),
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

